auth_enabled: false

server:
  http_listen_port: 3100
  http_server_read_timeout: 150m
  http_server_write_timeout: 150m
  log_level: info

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 1h
  max_chunk_age: 1h
  chunk_target_size: 1048576
  chunk_retain_period: 20m

schema_config:
  configs:
    - from: 2021-08-19
      store: cassandra
      object_store: filesystem
      schema: v11
      index:
        prefix: cassandra_table
        period: 24h

storage_config:
  cassandra:
    username: cassandra
    password: cassandra
    addresses: cassandra
    consistency: ONE
    auth: true
    keyspace: loki
  filesystem:
    directory: /loki/chunks
  index_queries_cache_config:
    redis:
      endpoint: redis:6379
      expiration: 1h

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 500
  ingestion_burst_size_mb: 500
  max_streams_per_user: 500000
  max_concurrent_tail_requests: 20
  max_query_series: 100000
  max_query_parallelism: 64

chunk_store_config:
  max_look_back_period: 720h
  cache_lookups_older_than: 24h

table_manager:
  retention_deletes_enabled: true
  retention_period: 720h

query_range:
  align_queries_with_step: true
  max_retries: 5
  split_queries_by_interval: 24h
  cache_results: true
  parallelise_shardable_queries: true
  results_cache:
    cache:
      redis:
        endpoint: redis:6379
        expiration: 48h
        db: 0

frontend:
  log_queries_longer_than: 5s
  downstream_url: http://0.0.0.0:3100
  compress_responses: true

querier:
  engine:
    timeout: 150m
    max_look_back_period: 150m
  query_ingesters_within: 3h
  max_concurrent: 25
  query_timeout: 150m
  extra_query_delay: 30s
